version: '3.8'

services:
  nrsc5-webplayer:
    build: .
    container_name: nrsc5-webplayer
    privileged: true
    ports:
      - "7430:7430"
    devices:
      - /dev:/dev
      - /run/udev:/run/udev:ro
    environment:
      - TZ=UTC
      - UDEV=1
    device_cgroup_rules:
      - 'c *:* rwm'
    network_mode: "bridge"
    restart: unless-stopped
    stdin_open: true   # Keeps STDIN open even if not attached
    tty: true          # Allocates a pseudo-TTY
