version: '3.8'

services:
  nrsc5-webplayer:
    build: .
    container_name: nrsc5-webplayer
    privileged: true
    ports:
      - "7430:7430"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - TZ=UTC
    network_mode: "bridge"
    restart: always
    stdin_open: true  
    tty: true   
    deploy:
      resources:
        limits:
          cpus: '1'           # Maximum 1 core - nrsc5 eats resources
          memory: 1096M       # Maximum 1GB of RAM
        reservations:
          cpus: '0.25'        # Request 25% of a single CPU core
          memory: 256M        # Request 256 Megabytes of RAM
